### ISSUE TITLE
Not working with Laravel 6

### ISSUE THREAD

**Issue by La1305** [GeneaLabs/nova-multi-tenant-manager#9]
Not working with Laravel 6 / Nova 2.3.1 / Hyn 5.5

It seems that Migrations missing - Table tenants not existing

```vagrant@homestead:~/code/wleads2$ php artisan tenant:create test test.de

   Illuminate\Database\QueryException  : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wleads2.tenants' doesn't exist (SQL: select * from `tenants` where (`domain` = test.de) limit 1)

  at /home/vagrant/code/wleads2/vendor/laravel/framework/src/Illuminate/Database/Connection.php:665
    661|         // If an exception occurs when attempting to run a query, we'll format the error
    662|         // message to include the bindings with SQL, which will make this exception a
    663|         // lot more helpful to the developer instead of just the database's errors.
    664|         catch (Exception $e) {
  > 665|             throw new QueryException(
    666|                 $query, $this->prepareBindings($bindings), $e
    667|             );
    668|         }
    669|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wleads2.tenants' doesn't exist")
      /home/vagrant/code/wleads2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:63

  2   PDOException::("SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wleads2.tenants' doesn't exist")
      /home/vagrant/code/wleads2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61

  Please use the argument -v to see more details.```

**Comment by mikebronner** [comment]
@La1305 It looks to me like you might not have Hyn 5.5 set up correctly. Does everything work without this package being installed?

**Comment by pjanprinsloo** [comment]
Same issue here. There doesn't seem to be a migration for table `tenants` present in the Hyn migrations.

**Comment by mikebronner** [comment]
@pjanprinsloo Thanks for providing additional input. I will try to test this over the next week or so. I have not had this error at all in my projects.

**Comment by pjanprinsloo** [comment]
> @pjanprinsloo Thanks for providing additional input. I will try to test this over the next week or so. I have not had this error at all in my projects.

Awesome, I will play around with a few scenarios. I have created a migration table `tenants` with  (`domain`, `name`, `website_id`, `updated_at`, `created_at`) and seems to have solved the issue.

**Comment by Dontorpedo** [comment]
same problem

**Comment by mikebronner** [comment]
Sorry for not coming back to this issue for such a long time. Much has changed in the interim, and this package is now only compatible with Laravel 8.
